# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:  [ master, development, experimental ]
  pull_request:
    branches:  [ master, development, experimental ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Test with Maven
      run: mvn install
    - name: Test examples
      run: |
        pwd
        ls -alt
        mvn dependency:tree
        ./lems src/test/resources/example1.xml -nogui
        ./lems src/test/resources/example2.xml -nogui
        ./lems src/test/resources/example3.xml -nogui
        ./lems src/test/resources/example4.xml -nogui
        ./lems src/test/resources/example5.xml -nogui
        ./lems src/test/resources/example6.xml -nogui
        ./lems src/test/resources/example7.xml -nogui
        ./lems src/test/resources/example8.xml -nogui
        ./lems src/test/resources/bounce-conditional.xml -nogui
        ./lems src/test/resources/bounce.xml -nogui
        ./lems src/test/resources/ex-flat.xml -nogui
        ./lems src/test/resources/test_regime_iaf.xml -nogui
        ./lems src/test/resources/ex-properties.xml -nogui
